name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: BigWigsMods/packager@release
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
